name: Full Stage Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target stage to deploy"
        required: true
        type: choice
        options:
          - staging
          - prod
      lambdas:
        description: |
          Comma-separated list of Lambdas to deploy (or 'all')  
          Available options:  
          - get_google_sign_in_url  
          - get_ebook_metadata
        required: true
        default: "all"

jobs:
  deploy-stage:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    env:
      REST_API_ID: 1u8zyys7vb
      REGION: ap-southeast-1
      ENV: ${{ github.event.inputs.environment }}
      ALLOWED_ORIGINS: ${{ vars.ALLOWED_ORIGINS }}
      COGNITO_CLIENT_ID: ${{ vars.COGNITO_CLIENT_ID }}
      COGNITO_DOMAIN: ${{ vars.COGNITO_DOMAIN }}
      COGNITO_REDIRECT_URI: ${{ vars.COGNITO_REDIRECT_URI }}
      BOOK_KEY: ${{ vars.BOOK_KEY }}
      EBOOK_BUCKET: ${{ vars.EBOOK_BUCKET }}
      ORIGIN: ${{ vars.ORIGIN }}
      USER_POOL_ID: ${{ vars.USER_POOL_ID }}
      OPTIONS_CORS_DOMAIN: ${{ vars.OPTIONS_CORS_DOMAIN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Deploy Lambdas
        run: |
          IFS=',' read -ra SELECTED <<< "${{ github.event.inputs.lambdas }}"

          if [[ "${{ github.event.inputs.lambdas }}" == "all" ]]; then
            echo "Deploying ALL lambdas..."
            bash .github/scripts/deploy_lambdas.sh all
          else
            for lambda in "${SELECTED[@]}"; do
              lambda=$(echo "$lambda" | xargs) # trim spaces
              echo "Deploying $lambda..."
              bash .github/scripts/deploy_lambdas.sh select "$lambda"
            done
          fi

      - name: Update API Gateway routes
        run: |
          echo "Updating API Gateway routes for ${{ github.event.inputs.environment }}..."
          # Add your route update logic here
