name: Lambda Folder Change Deployment

on:
  push:
    branches:
      - main
      - 'staging*'

jobs:
  deploy-lambdas:
    runs-on: ubuntu-latest

    # Environment variables will be populated dynamically in a step
    env:
      REGION: ap-southeast-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment and load variables
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            ENV="prod"
          else
            ENV="staging"
          fi
          echo "ENV=$ENV" >> $GITHUB_ENV

          # Map environment variables to GitHub secrets or vars for the selected ENV
          echo "ALLOWED_ORIGINS=${{ vars.ALLOWED_ORIGINS }}" >> $GITHUB_ENV
          echo "COGNITO_CLIENT_ID=${{ vars.COGNITO_CLIENT_ID }}" >> $GITHUB_ENV
          echo "COGNITO_DOMAIN=${{ vars.COGNITO_DOMAIN }}" >> $GITHUB_ENV
          echo "COGNITO_REDIRECT_URI=${{ vars.COGNITO_REDIRECT_URI }}" >> $GITHUB_ENV
          echo "BOOK_KEY=${{ vars.BOOK_KEY }}" >> $GITHUB_ENV
          echo "EBOOK_BUCKET=${{ vars.EBOOK_BUCKET }}" >> $GITHUB_ENV
          echo "ORIGIN=${{ vars.ORIGIN }}" >> $GITHUB_ENV
          echo "USER_POOL_ID=${{ vars.USER_POOL_ID }}" >> $GITHUB_ENV
          echo "OPTIONS_CORS_DOMAIN=${{ vars.OPTIONS_CORS_DOMAIN }}" >> $GITHUB_ENV

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Detect changed Lambda folders
        id: changed
        run: |
          CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^lambdas/' | cut -d'/' -f2 | sort -u || true)
          echo "CHANGED_LAMBDAS=$CHANGED" >> $GITHUB_ENV

      - name: Deploy changed Lambdas
        if: env.CHANGED_LAMBDAS != ''
        run: |
          IFS=' ' read -ra LAMBDAS <<< "${CHANGED_LAMBDAS}"
          for lambda in "${LAMBDAS[@]}"; do
            echo "Deploying $lambda..."
            bash .github/scripts/deploy_lambdas.sh select "$lambda"
