name: Lambda Folder Change Deployment

on:
  push:
    branches:
      - main
      - 'staging*'
      - 'feature/*'

jobs:
  deploy-lambdas:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'staging' }}

    env:
      REGION: ap-southeast-1
      REST_API_ID: 1u8zyys7vb
      ALLOWED_ORIGINS: ${{ vars.ALLOWED_ORIGINS }}
      COGNITO_CLIENT_ID: ${{ vars.COGNITO_CLIENT_ID }}
      COGNITO_DOMAIN: ${{ vars.COGNITO_DOMAIN }}
      COGNITO_REDIRECT_URI: ${{ vars.COGNITO_REDIRECT_URI }}
      BOOK_KEY: ${{ vars.BOOK_KEY }}
      EBOOK_BUCKET: ${{ vars.EBOOK_BUCKET }}
      ORIGIN: ${{ vars.ORIGIN }}
      USER_POOL_ID: ${{ vars.USER_POOL_ID }}
      OPTIONS_CORS_DOMAIN: ${{ vars.OPTIONS_CORS_DOMAIN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Detect changed Lambda folders
        id: changed
        run: |
          echo "Detecting changed Lambda folders..."
          CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^lambdas/' | cut -d'/' -f2 | sort -u || true)
          if [[ -z "$CHANGED" ]]; then
            echo "No Lambda changes detected."
            echo "CHANGED_LAMBDAS=" >> $GITHUB_ENV
          else
            echo "Changed lambdas: $CHANGED"
            echo "CHANGED_LAMBDAS=$CHANGED" >> $GITHUB_ENV

      - name: Deploy changed Lambdas
        if: env.CHANGED_LAMBDAS != ''
        run: |
          IFS=' ' read -ra LAMBDAS <<< "${CHANGED_LAMBDAS}"
          for lambda in "${LAMBDAS[@]}"; do
            echo "Deploying $lambda..."
            bash .github/scripts/deploy_lambdas.sh select "$lambda"
